services:
  api-gateway:
    image: tert62/dsc-api-gateway:day12
    build: !reset null

  deploy-service:
    image: tert62/dsc-deploy-service:day12
    build: !reset null

  log-service:
    image: tert62/dsc-log-service:day12
    build: !reset null
