apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: deploy-status-checker
  labels:
    app: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-cm
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DEPLOY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DEPLOY_DB_PASSWORD
            - name: LOG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: LOG_DB_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: init-script
          configMap:
            name: postgres-init-cm
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
